CREATE TABLE if not exists medicine(med_id BIGINT,inputfullname VARCHAR(500),mType VARCHAR(500),mDescription VARCHAR(500),mPrice INT,mQuantity VARCHAR(500),mCompany VARCHAR(500),mDose INT);

INSERT INTO medicine VALUES('1','Varivax','Ea14vM6stV','Aquamarine',44,'Yearly','Leadertech Consulting',3);
INSERT INTO medicine VALUES('2','Herceptin','BmawOLVeVb','Cerise',31,'Daily','CarMax',1);
INSERT INTO medicine VALUES('3','Zovirax','ZXpp9C71OO','Peach',60,'Rarely','BuzzFeed',3);
INSERT INTO medicine VALUES('4','Aspirin','WcHNASz2EX','Amethyst',32,'Seldom','Biolife Grup',2);
INSERT INTO medicine VALUES('5','Maxalt','LvCs2Ao8pi','Apricot',98,'Once','Mars',4);
INSERT INTO medicine VALUES('6','Coldrex','wV7106pGhx','Sky blue',62,'Rarely','Biolife Grup',1);
INSERT INTO medicine VALUES('7','Tylenol','0Satz6IWyJ','White',46,'Weekly','Boeing',4);
INSERT INTO medicine VALUES('8','Unisom','YGhepg4OF5','Carmine',8,'Monthly','Coca-Cola Company',3);
INSERT INTO medicine VALUES('9','MidNite','g4IzSOm0Nk','Silver',69,'Monthly','Vodafone',2);
INSERT INTO medicine VALUES('10','Zovirax','CQOWGh6UXM','Gold',90,'Weekly','Comodo',4);
INSERT INTO medicine VALUES('11','Maxalt','of60s5BJdq','Sienna',7,'Rarely','Vodafone',4);
INSERT INTO medicine VALUES('12','Gravol','keDJxI688y','Aquamarine',10,'Often','Zepter',1);
INSERT INTO medicine VALUES('13','Exact','nRC2Rf9GOE','Purple',41,'Daily','BuzzFeed',4);
INSERT INTO medicine VALUES('14','Exact','XwUQ9y8gj7','Rust',90,'Rarely','Amazon.com',3);
INSERT INTO medicine VALUES('15','Maxalt','kGbLK6lEf6','Gray',72,'Daily','AECOM',3);
INSERT INTO medicine VALUES('16','Benadryl','6RtxYzKzSg','Maroon',31,'Often','Carrefour',3);
INSERT INTO medicine VALUES('17','Ibuprofen','fHzJap9aLP','Olive',4,'Never','21st Century Fox',2);
INSERT INTO medicine VALUES('18','Band-Aid','Pw7MMvXv6m','Purple',64,'Often','Global Print',2);
INSERT INTO medicine VALUES('19','Zoloft','VmNHripRSS','Magenta',14,'Yearly','Danone',4);
INSERT INTO medicine VALUES('20','Band-Aid','PQE0HYGtuE','Rosewood',81,'Weekly','Apple Inc.',4);
INSERT INTO medicine VALUES('21','Amaryl','xVrQCJVqGp','Gray',89,'Once','Vodafone',3);
INSERT INTO medicine VALUES('22','Pepcid','q0YWNlS6gd','Cerise',63,'Monthly','Boeing',3);
INSERT INTO medicine VALUES('23','Symbicort','fsVsZpAG4X','Auburn',45,'Rarely','Team Guard SRL',3);
INSERT INTO medicine VALUES('24','Zetia','WXI47bqMDv','Auburn',55,'Seldom','Zepter',2);
INSERT INTO medicine VALUES('25','Lisinopril','K7Ya29aA0S','Aquamarine',82,'Seldom','Boeing',2);
INSERT INTO medicine VALUES('26','Unisom','2zQ7tk9DCJ','Gold',63,'Never','ENEL',2);
INSERT INTO medicine VALUES('27','Advil','BgRgxKoW7H','Peach',66,'Never','Boeing',2);
INSERT INTO medicine VALUES('28','Abilify','UZp7cYfk7U','Salmon',73,'Monthly','ExxonMobil',1);
INSERT INTO medicine VALUES('29','Zoloft','9PxUi5gsL3','Fuchsia',61,'Rarely','Apple Inc.',1);
INSERT INTO medicine VALUES('30','Exact','xbTfvVunAr','Amethyst',46,'Seldom','Amazon.com',1);
INSERT INTO medicine VALUES('31','Advil','BppuDBoZ37','Olive',55,'Monthly','BuzzFeed',1);
INSERT INTO medicine VALUES('32','Singulair','QN63dknofK','Maroon',86,'Monthly','Comodo',4);
INSERT INTO medicine VALUES('33','Miralax','1xk1pUGvw4','Lime',81,'Often','Team Guard SRL',1);
INSERT INTO medicine VALUES('34','Vioxx','n6Mj8IrbBB','Red',90,'Weekly','ExxonMobil',1);
INSERT INTO medicine VALUES('35','Pepcid','CeqlSM76GK','Ultramarine',56,'Never','DynCorp',1);
INSERT INTO medicine VALUES('36','Novolin','6LOZ0VStGJ','Ruby',64,'Yearly','Vodafone',1);
INSERT INTO medicine VALUES('37','Zetril','1vwEfmza9Q','Capri',81,'Yearly','It Smart Group',2);
INSERT INTO medicine VALUES('38','Abilify','657gjn8qM6','Cadet blue',14,'Monthly','Erickson',4);
INSERT INTO medicine VALUES('39','Amaryl','GIrMC9xTVy','Green',58,'Seldom','UPC',3);
INSERT INTO medicine VALUES('40','Fosamax','rmrJPhaNxG','Purple',56,'Once','Facebook',1);

